"""landscape not unique

Revision ID: b73d940b9898
Revises: 51eba48baa65
Create Date: 2024-06-29 02:23:39.982399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73d940b9898'
down_revision: Union[str, None] = '51eba48baa65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_landscapes_name', table_name='landscapes')
    op.create_index(op.f('ix_landscapes_name'), 'landscapes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landscapes_name'), table_name='landscapes')
    op.create_index('ix_landscapes_name', 'landscapes', ['name'], unique=True)
    # ### end Alembic commands ###
